// Generated by gencpp from file beginner_tutorials/single.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SINGLE_H
#define BEGINNER_TUTORIALS_MESSAGE_SINGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct single_
{
  typedef single_<ContainerAllocator> Type;

  single_()
    : height()
    , align()
    , area()  {
    }
  single_(const ContainerAllocator& _alloc)
    : height(_alloc)
    , align(_alloc)
    , area(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _height_type;
  _height_type height;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _align_type;
  _align_type align;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::beginner_tutorials::single_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::single_<ContainerAllocator> const> ConstPtr;

}; // struct single_

typedef ::beginner_tutorials::single_<std::allocator<void> > single;

typedef boost::shared_ptr< ::beginner_tutorials::single > singlePtr;
typedef boost::shared_ptr< ::beginner_tutorials::single const> singleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::single_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::single_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/mayuresh/search_and_rescue/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::single_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::single_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::single_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::single_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::single_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::single_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::single_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1b42f61dd256ab5fb256ea59e23417b";
  }

  static const char* value(const ::beginner_tutorials::single_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1b42f61dd256ab5ULL;
  static const uint64_t static_value2 = 0xfb256ea59e23417bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::single_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/single";
  }

  static const char* value(const ::beginner_tutorials::single_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::single_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] height\n"
"int32[] align\n"
"float32[] area\n"
;
  }

  static const char* value(const ::beginner_tutorials::single_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::single_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.align);
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct single_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::single_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::single_<ContainerAllocator>& v)
  {
    s << indent << "height[]" << std::endl;
    for (size_t i = 0; i < v.height.size(); ++i)
    {
      s << indent << "  height[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.height[i]);
    }
    s << indent << "align[]" << std::endl;
    for (size_t i = 0; i < v.align.size(); ++i)
    {
      s << indent << "  align[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.align[i]);
    }
    s << indent << "area[]" << std::endl;
    for (size_t i = 0; i < v.area.size(); ++i)
    {
      s << indent << "  area[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.area[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SINGLE_H
