// Generated by gencpp from file beginner_tutorials/vel.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_VEL_H
#define BEGINNER_TUTORIALS_MESSAGE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct vel_
{
  typedef vel_<ContainerAllocator> Type;

  vel_()
    : ref_left(0)
    , ref_right(0)  {
    }
  vel_(const ContainerAllocator& _alloc)
    : ref_left(0)
    , ref_right(0)  {
  (void)_alloc;
    }



   typedef int32_t _ref_left_type;
  _ref_left_type ref_left;

   typedef int32_t _ref_right_type;
  _ref_right_type ref_right;





  typedef boost::shared_ptr< ::beginner_tutorials::vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::vel_<ContainerAllocator> const> ConstPtr;

}; // struct vel_

typedef ::beginner_tutorials::vel_<std::allocator<void> > vel;

typedef boost::shared_ptr< ::beginner_tutorials::vel > velPtr;
typedef boost::shared_ptr< ::beginner_tutorials::vel const> velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/mayuresh/search_and_rescue/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3607ebf3a337eebee6a6822feb14efcc";
  }

  static const char* value(const ::beginner_tutorials::vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3607ebf3a337eebeULL;
  static const uint64_t static_value2 = 0xe6a6822feb14efccULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/vel";
  }

  static const char* value(const ::beginner_tutorials::vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ref_left\n"
"int32 ref_right \n"
;
  }

  static const char* value(const ::beginner_tutorials::vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ref_left);
      stream.next(m.ref_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::vel_<ContainerAllocator>& v)
  {
    s << indent << "ref_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ref_left);
    s << indent << "ref_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ref_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_VEL_H
